[package]
name = "interactive_skia"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
velox-dom = { path = "../../velox-dom" }
velox-style = { path = "../../velox-style" }
velox-renderer = { path = "../../velox-renderer", features = ["skia-native"] }
